name: Percipe
options:
  deploymentTarget:
    iOS: 17.0
  defaultConfig: Release
packages:
  swift-collections:
    url: https://github.com/apple/swift-collections
    version: 1.0.3
  SwiftUI-Shimmer:
    url: https://github.com/markiv/SwiftUI-Shimmer
    version: 1.1.0
  ExpandableText:
    url: https://github.com/NuPlay/ExpandableText
    version: 1.2.0
  swiftui-cached-async-image:
    url: https://github.com/lorenzofiamingo/swiftui-cached-async-image
    version: 2.1.1
  SwiftUI-Tooltip:
    url: https://github.com/quassum/SwiftUI-Tooltip
    version: 1.3.0
targets:
  Percipe:
    settings:
      type: application
      base:
        #DEVELOPMENT_TEAM: "7PLLZ436SG"
        PRODUCT_BUNDLE_IDENTIFIER: "de.percipe"
        PRODUCT_NAME: Percipe
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    type: application
    scheme:
      parallelizeBuild: true
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    platform: iOS
    sources:
      - path: Percipe
        name: Percipe
    dependencies:
      - package: swift-collections
        product: OrderedCollections
      - package: SwiftUI-Shimmer
        product: Shimmer
      - package: ExpandableText
        product: ExpandableText
      - package: swiftui-cached-async-image
        product: CachedAsyncImage
      - package: SwiftUI-Tooltip
        product: SwiftUITooltip
